'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {createStore}=require('../contracts/store');
const {createHandler}=require('../contracts/routes');
test('real contract HTTP API enforces session, origin, object access and revision checks',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'contract-http-'));
 const users={staff:{user:'staff',role:'staff'},other:{user:'other',role:'staff'},owner:{user:'owner',role:'owner'}};
 const handler=createHandler({store:createStore(root),origin:'https://thevillamanagers.cloud',resolveActor:async req=>users[req.headers['x-test-user']]||null});
 const server=http.createServer((req,res)=>handler(req,res).catch(()=>{res.writeHead(500);res.end();}));
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));await fs.rm(root,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${server.address().port}/api/admin/contracts`;
 const request=(suffix='',method='GET',body,user='staff',origin='https://thevillamanagers.cloud')=>fetch(base+suffix,{method,headers:{'x-test-user':user,Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 assert.equal((await request('','GET',undefined,'nobody')).status,401);
 assert.equal((await request('','GET',undefined,'owner')).status,403);
 assert.equal((await request('','POST',{},'staff','https://evil.test')).status,403);
 assert.equal((await request('','POST',{},'staff','')).status,403);
 const made=await request('','POST',{});assert.equal(made.status,201);const draft=await made.json();
 assert.equal((await request('/'+draft.id,'GET',undefined,'other')).status,404);
 const update=await request('/'+draft.id,'PATCH',{revision:0,fields:{'property.name':'Synthetic Villa'}});assert.equal(update.status,200);
 assert.equal((await update.json()).data['property.name'],'Synthetic Villa');
 assert.equal((await request('/'+draft.id,'PATCH',{revision:0,fields:{'property.name':'Stale'}})).status,409);
 assert.equal((await request('/'+draft.id,'PATCH',{revision:1,fields:{'bank.name':'Changed'}})).status,422);
 assert.equal((await request('/'+draft.id,'PATCH',{revision:1,fields:{},createdBy:'other'})).status,422);
 const read=await request('/'+draft.id);assert.equal(read.headers.get('cache-control'),'no-store');
 assert.equal((await read.json()).revision,1);
 assert.equal((await request('/not-a-contract')).status,404);
});
