const { google } = require('googleapis');
const config = require('../config/integrations.json');
const d = config.docs;

function getAuth() {
  const auth = new google.auth.OAuth2(d.client_id, d.client_secret);
  auth.setCredentials({ refresh_token: d.refresh_token });
  return auth;
}

async function createDoc(title, content) {
  try {
    const docs = google.docs({ version: 'v1', auth: getAuth() });
    const drive = google.drive({ version: 'v3', auth: getAuth() });
    const doc = await docs.documents.create({ requestBody: { title } });
    const docId = doc.data.documentId;
    if (content) {
      await docs.documents.batchUpdate({
        documentId: docId,
        requestBody: { requests: [{ insertText: { location: { index: 1 }, text: content } }] }
      });
    }
    const file = await drive.files.get({ fileId: docId, fields: 'webViewLink' });
    return { docId, title, link: file.data.webViewLink };
  } catch (err) { console.error('Docs create error:', err.message); return null; }
}

async function readDoc(documentId) {
  try {
    const docs = google.docs({ version: 'v1', auth: getAuth() });
    const res = await docs.documents.get({ documentId });
    const content = res.data.body.content
      .map(el => el.paragraph?.elements?.map(e => e.textRun?.content || '').join('') || '')
      .join('');
    return { title: res.data.title, content, documentId };
  } catch (err) { console.error('Docs read error:', err.message); return null; }
}

async function updateDoc(documentId, findText, replaceText) {
  try {
    const docs = google.docs({ version: 'v1', auth: getAuth() });
    await docs.documents.batchUpdate({
      documentId,
      requestBody: {
        requests: [{ replaceAllText: { containsText: { text: findText, matchCase: false }, replaceText } }]
      }
    });
    return true;
  } catch (err) { console.error('Docs update error:', err.message); return false; }
}

async function createContract(guestName, villaName, checkIn, checkOut, price, extras = '') {
  const content = `VILLA RENTAL CONTRACT
The Villa Managers

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

GUEST INFORMATION
Guest Name: ${guestName}
Check-in: ${checkIn}
Check-out: ${checkOut}

PROPERTY DETAILS
Villa: ${villaName}
Total Price: ${price}
${extras ? 'Additional Services: ' + extras : ''}

TERMS & CONDITIONS

1. CHECK-IN/CHECK-OUT
   Check-in time: 14:00 | Check-out time: 12:00

2. PAYMENT
   Full payment required before check-in.

3. SECURITY DEPOSIT
   A refundable security deposit is required upon arrival.

4. CANCELLATION POLICY
   - 30+ days: Full refund
   - 14-29 days: 50% refund
   - Less than 14 days: No refund

5. HOUSE RULES
   - No smoking inside the villa
   - No parties without prior approval
   - Maximum occupancy must be respected
   - Pets subject to prior approval

6. DAMAGES
   Guest is liable for any damages caused during the stay.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURES

Guest: _________________________ Date: _________

The Villa Managers: _____________ Date: _________

Generated by TVMbot | thevillamanagers.cloud`;

  return await createDoc(`Contract - ${guestName} - ${villaName} - ${checkIn}`, content);
}

module.exports = { createDoc, readDoc, updateDoc, createContract };
